# Generated by Django 6.0.4 on 2026-04-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoilo_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='id',
        ),
        migrations.RemoveField(
            model_name='social_media',
            name='id',
        ),
        migrations.RemoveField(
            model_name='works',
            name='id',
        ),
        migrations.AddField(
            model_name='contact',
            name='Contact_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='message',
            name='message_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='skills',
            name='skills_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='social_media',
            name='media_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='works',
            name='works_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
