# Generated by Django 6.0.4 on 2026-04-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoilo_App', '0002_remove_contact_id_remove_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='description',
            field=models.CharField(default='description about the work'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=50),
        ),
    ]
