# Generated by Django 6.0.4 on 2026-04-24 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoilo_App', '0003_works_description_alter_message_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='Liked_work', to=settings.AUTH_USER_MODEL),
        ),
    ]
