# Generated by Django 6.0.4 on 2026-04-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoilo_App', '0004_works_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='works',
            name='likes',
        ),
        migrations.AddField(
            model_name='works',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
